
version: '3.4'

services:
  ultimatepricebot:
    image: ultimatepricebot
    restart: always
    build:
      context: .
      dockerfile: src/ICCD.UltimatePriceBot.App/Dockerfile
    environment:
      - APP_ENVIRONMENT=Production